# This is a workflow use when we create a pull request

name: Build - Merge

# Controls when the action will run.
on:
  # Triggers the workflow on main/develop branch based pull request event
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.png'
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    permissions:
      contents: read
      id-token: write # Mandatory
      pull-requests: write # Mandatory
      statuses: write # Mandatory
      issues: write # Mandatory
      checks: write # Mandatory
      packages: write # needed for push of package
      repository-projects: read

    strategy:
      matrix:
        node-version: [ 24.x ]

    name: Test - Analyze apps
    steps:
      - uses: actions/checkout@v4

      - id: build-app
        name: Build App
        uses: ./.github/actions/build-app
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_VERSION: ${{ matrix.node-version }}

      - id: build-images
        name: App - Build image
        uses: ./.github/actions/build-images
        with:
          MODULE: "app"
          GITHUB_SHA: "${{ github.sha }}"
          GITHUB_OUTPUT: $GITHUB_OUTPUT